-- infinidb

CREATE TABLE `trend_campaign` (
	`campaign_id` INT(11) NOT NULL DEFAULT '0',
	`product_id` INT(11) NOT NULL DEFAULT '0',
	`policy_id` INT(11) NOT NULL DEFAULT '0',
	`package_id` INT(11) NOT NULL DEFAULT '0',
	`creative_id` INT(11) NOT NULL DEFAULT '0',
	`spot_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`whisky_id` INT(11) NOT NULL DEFAULT '0',
	`spot_channel_id` INT(11) NOT NULL DEFAULT '0',
	`medium_id` INT(11) NOT NULL DEFAULT '0',
	`channel_type_id` INT(11) NOT NULL DEFAULT '0',
	`channel_id` INT(11) NOT NULL DEFAULT '0',
	`platform_id` INT(11) NOT NULL DEFAULT '0',
	`date` INT(11) NOT NULL DEFAULT '0',
	`hour` TINYINT(4) NOT NULL DEFAULT '0',
	`user_id` INT(11) NOT NULL DEFAULT '0',
	`ips` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`impressions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`new_impressions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`visitors` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`new_visitors` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`reviews` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`insights` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`cost` DECIMAL(18,6) UNSIGNED NOT NULL DEFAULT '0.000000',
	`cost_over` DECIMAL(18,6) UNSIGNED NOT NULL DEFAULT '0.000000',
	`cost_over2` DECIMAL(18,6) UNSIGNED NOT NULL DEFAULT '0.000000',
	`pagepixels` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`clicks` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`spot_screen_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`spot_size_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`reserve0` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`reserve1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`reserve2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`reserve3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`reserve4` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`b_ips` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_pageviews` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_sessions` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_visitors` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_new_visitors` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_bounces` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_pagepixels` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_staytime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_loadtime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_click` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_clicks` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_input` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_inclick` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_outclick` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_stop` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_regs` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_logins` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_reserve0` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_reserve1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_reserve2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_reserve3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_reserve4` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_active_visitors` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`b_new_pageviews` INT(10) UNSIGNED NOT NULL DEFAULT '0'
)
ENGINE=infinidb;


-- infobright

CREATE TABLE `trend_campaign` (
  `campaign_id` int(11) NOT NULL DEFAULT '0',
  `product_id` int(11) NOT NULL DEFAULT '0',
  `policy_id` int(11) NOT NULL DEFAULT '0',
  `package_id` int(11) NOT NULL DEFAULT '0',
  `creative_id` int(11) NOT NULL DEFAULT '0',
  `spot_id` bigint(20) NOT NULL DEFAULT '0',
  `whisky_id` int(11) NOT NULL DEFAULT '0',
  `spot_channel_id` int(11) NOT NULL DEFAULT '0',
  `medium_id` int(11) NOT NULL DEFAULT '0',
  `channel_type_id` int(11) NOT NULL DEFAULT '0',
  `channel_id` int(11) NOT NULL DEFAULT '0',
  `platform_id` int(11) NOT NULL DEFAULT '0',
  `date` int(11) NOT NULL DEFAULT '0',
  `hour` tinyint(4) NOT NULL DEFAULT '0',
  `user_id` int(11) NOT NULL DEFAULT '0',
  `ips` int(11) NOT NULL DEFAULT '0',
  `impressions` int(11) NOT NULL DEFAULT '0',
  `new_impressions` int(11) NOT NULL DEFAULT '0',
  `visitors` int(11) NOT NULL DEFAULT '0',
  `new_visitors` int(11) NOT NULL DEFAULT '0',
  `reviews` int(11) NOT NULL DEFAULT '0',
  `insights` int(11) NOT NULL DEFAULT '0',
  `cost` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `cost_over` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `cost_over2` decimal(18,6) NOT NULL DEFAULT '0.000000',
  `pagepixels` int(11) NOT NULL DEFAULT '0',
  `clicks` int(11) NOT NULL DEFAULT '0',
  `spot_screen_id` int(10) NOT NULL DEFAULT '0',
  `spot_size_id` int(10) NOT NULL DEFAULT '0',
  `reserve0` int(11) NOT NULL DEFAULT '0',
  `reserve1` int(11) NOT NULL DEFAULT '0',
  `reserve2` int(11) NOT NULL DEFAULT '0',
  `reserve3` int(11) NOT NULL DEFAULT '0',
  `reserve4` int(11) NOT NULL DEFAULT '0',
  `b_ips` int(10) NOT NULL DEFAULT '0',
  `b_pageviews` int(10) NOT NULL DEFAULT '0',
  `b_sessions` int(10) NOT NULL DEFAULT '0',
  `b_visitors` int(10) NOT NULL DEFAULT '0',
  `b_new_visitors` int(10) NOT NULL DEFAULT '0',
  `b_bounces` int(10) NOT NULL DEFAULT '0',
  `b_pagepixels` int(10) NOT NULL DEFAULT '0',
  `b_staytime` int(10) NOT NULL DEFAULT '0',
  `b_loadtime` int(10) NOT NULL DEFAULT '0',
  `b_click` int(10) NOT NULL DEFAULT '0',
  `b_clicks` int(10) NOT NULL DEFAULT '0',
  `b_input` int(10) NOT NULL DEFAULT '0',
  `b_inclick` int(10) NOT NULL DEFAULT '0',
  `b_outclick` int(10) NOT NULL DEFAULT '0',
  `b_stop` int(10) NOT NULL DEFAULT '0',
  `b_regs` int(10) NOT NULL DEFAULT '0',
  `b_logins` int(10) NOT NULL DEFAULT '0',
  `b_reserve0` int(10) NOT NULL DEFAULT '0',
  `b_reserve1` int(10) NOT NULL DEFAULT '0',
  `b_reserve2` int(10) NOT NULL DEFAULT '0',
  `b_reserve3` int(10) NOT NULL DEFAULT '0',
  `b_reserve4` int(10) NOT NULL DEFAULT '0',
  `b_active_visitors` int(10) NOT NULL DEFAULT '0',
  `b_new_pageviews` int(10) NOT NULL DEFAULT '0'
) ENGINE=BRIGHTHOUSE DEFAULT CHARSET=utf8;
